/*--------------------------------------------------------------------------------
PASO 1: CREACION DE ENTORNO
--------------------------------------------------------------------------------*/

--ROLES:
CREATE ROLE PRY2205_ROL_D; -- Rol de desarrollo para el usuario 1
CREATE ROLE PRY2205_ROL_P; -- Rol de produccion para el usuario 2

DROP ROLE PRY2205_ROL_D;
--ASIGNACION DE PRIVILEGIOS A LOS ROLES
-- PRIVILEGIOS PARA EL ROL D
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE ANY INDEX, CREATE SYNONYM, CREATE PUBLIC SYNONYM, DROP PUBLIC SYNONYM TO PRY2205_ROL_D;

--PRIVILEGIOS PARA EL ROL P
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER TO PRY2205_ROL_P;

-------------------------------------------------------------------------------------

/*USUARIOS*/

--USUARIO 1: DUEÑO DEL ESQUEMA
CREATE USER PRY2205_USER1 IDENTIFIED BY "OWNER_duoc.2025"
DEFAULT TABLESPACE DATA
QUOTA UNLIMITED ON DATA;


--USUARIO 2: CONSULTOR (debido a que solo es un consultor de datos, se le aignara una cuota especificade almacenamiento "seguro" y que es suficiente para este tipo de trabajo especificado en el proyecto)
CREATE USER PRY2205_USER2 IDENTIFIED BY "CONSULTOR_duoc.2025"
DEFAULT TABLESPACE DATA
QUOTA 100M ON DATA;

/* ASIGNACION DE ROLER A LOS USUARIOS */
GRANT PRY2205_ROL_D TO PRY2205_USER1; -- ROL D ASIGNADO AL USUARIO 1
GRANT PRY2205_ROL_P TO PRY2205_USER2; -- ROL P ASIGNADO AL USUARIO 2
--CONFIRMAMOS LOS CAMBIOS
COMMIT;

/*SINONIMOS Y PERMISOS DE OBJETO */
--1.-DAR PERMISOS DE LECTURA (SELECT) AL ROL P SOBRE LAS TABLAS DEL USER1
GRANT SELECT ON PRY2205_USER1.LIBRO TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.EJEMPLAR TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.PRESTAMO TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.ALUMNO TO PRY2205_ROL_P; -- este sera necesario para los nombres
GRANT SELECT ON PRY2205_USER1.CARRERA TO PRY2205_ROL_P; 
GRANT SELECT ON PRY2205_USER1.EMPLEADO TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.REBAJA_MULTA TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.VALOR_MULTA_PRESTAMO TO PRY2205_ROL_P;

--2.- SINONIMOS PUBLICOS
CREATE OR REPLACE PUBLIC SYNONYM SYN_LIBRO FOR PRY2205_USER1.LIBRO;
CREATE OR REPLACE PUBLIC SYNONYM SYN_EJEMPLAR FOR PRY2205_USER1.EJEMPLAR;
CREATE OR REPLACE PUBLIC SYNONYM SYN_PRESTAMO FOR PRY2205_USER1.PRESTAMO;
CREATE OR REPLACE PUBLIC SYNONYM SYN_ALUMNO FOR PRY2205_USER1.ALUMNO;
CREATE OR REPLACE PUBLIC SYNONYM SYN_CARRERA FOR PRY2205_USER1.CARRERA;
CREATE OR REPLACE PUBLIC SYNONYM SYN_EMPLEADO FOR PRY2205_USER1.EMPLEADO;
CREATE OR REPLACE PUBLIC SYNONYM SYN_REBAJA FOR PRY2205_USER1.REBAJA;
CREATE OR REPLACE PUBLIC SYNONYM SYN_VAL_MULTA FOR PRY2205_USER1.VALOR_MULTA_PRESTAMO;

COMMIT;


