/*=================================================================
SEMANA 8: CONTROL DE ACCESO Y OPTIMIZACION
===================================================================*/

--BLOQUE 1: USER ADMIN / SYSTEM
-- CREACION DE USUARIOS, ROLES Y SINONIMOS

--ROLES:
CREATE ROLE PRY2205_ROL_D; -- Rol de desarrollo para el usuario 1
CREATE ROLE PRY2205_ROL_P; -- Rol de produccion para el usuario 2

DROP ROLE PRY2205_ROL_D;
--ASIGNACION DE PRIVILEGIOS A LOS ROLES
-- PRIVILEGIOS PARA EL ROL D
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE ANY INDEX, CREATE SYNONYM, CREATE PUBLIC SYNONYM, DROP PUBLIC SYNONYM TO PRY2205_ROL_D;

--PRIVILEGIOS PARA EL ROL P
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER TO PRY2205_ROL_P;

-------------------------------------------------------------------------------------

/*USUARIOS*/

--USUARIO 1: DUEÑO DEL ESQUEMA
CREATE USER PRY2205_USER1 IDENTIFIED BY "OWNER_duoc.2025"
DEFAULT TABLESPACE DATA
QUOTA UNLIMITED ON DATA;


--USUARIO 2: CONSULTOR (debido a que solo es un consultor de datos, se le aignara una cuota especificade almacenamiento "seguro" y que es suficiente para este tipo de trabajo especificado en el proyecto)
CREATE USER PRY2205_USER2 IDENTIFIED BY "CONSULTOR_duoc.2025"
DEFAULT TABLESPACE DATA
QUOTA 100M ON DATA;

/* ASIGNACION DE ROLER A LOS USUARIOS */
GRANT PRY2205_ROL_D TO PRY2205_USER1; -- ROL D ASIGNADO AL USUARIO 1
GRANT PRY2205_ROL_P TO PRY2205_USER2; -- ROL P ASIGNADO AL USUARIO 2
--CONFIRMAMOS LOS CAMBIOS
COMMIT;

/*SINONIMOS Y PERMISOS DE OBJETO */
--1.-DAR PERMISOS DE LECTURA (SELECT) AL ROL P SOBRE LAS TABLAS DEL USER1
GRANT SELECT ON PRY2205_USER1.LIBRO TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.EJEMPLAR TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.PRESTAMO TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.ALUMNO TO PRY2205_ROL_P; -- este sera necesario para los nombres
GRANT SELECT ON PRY2205_USER1.CARRERA TO PRY2205_ROL_P; 
GRANT SELECT ON PRY2205_USER1.EMPLEADO TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.REBAJA_MULTA TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.VALOR_MULTA_PRESTAMO TO PRY2205_ROL_P;

--2.- SINONIMOS PUBLICOS
CREATE OR REPLACE PUBLIC SYNONYM SYN_LIBRO FOR PRY2205_USER1.LIBRO;
CREATE OR REPLACE PUBLIC SYNONYM SYN_EJEMPLAR FOR PRY2205_USER1.EJEMPLAR;
CREATE OR REPLACE PUBLIC SYNONYM SYN_PRESTAMO FOR PRY2205_USER1.PRESTAMO;
CREATE OR REPLACE PUBLIC SYNONYM SYN_ALUMNO FOR PRY2205_USER1.ALUMNO;
CREATE OR REPLACE PUBLIC SYNONYM SYN_CARRERA FOR PRY2205_USER1.CARRERA;
CREATE OR REPLACE PUBLIC SYNONYM SYN_EMPLEADO FOR PRY2205_USER1.EMPLEADO;
CREATE OR REPLACE PUBLIC SYNONYM SYN_REBAJA FOR PRY2205_USER1.REBAJA;
CREATE OR REPLACE PUBLIC SYNONYM SYN_VAL_MULTA FOR PRY2205_USER1.VALOR_MULTA_PRESTAMO;

COMMIT;

/*=========================================================================================
NLOQUE 2: USER2 
INFORMES DE STOCK
===========================================================================================*/

-- SECUENCIA PARA CADA VEZ QUE SE INSERTA UNA FILA EN LA TABLA
CREATE SEQUENCE SQ_CONTROL_STOCK START WITH 1 INCREMENT BY 1;

--CREAMOS LA TABLA PARA DE RESULTADOS
CREATE TABLE CONTROL_STOCK_LIBROS (
    ID_CONTROL NUMBER PRIMARY KEY,
    LIBRO_ID NUMBER,
    NOMBRE_LIBRO VARCHAR2(100),
    TOTAL_EJEMPLARES NUMBER,
    EN_PRESTAMO NUMBER,
    DISNIBLES NUMBER,
    PORCENTAJE_PRESTAMOS NUMBER(5,2),
    STOCK_CRITICO VARCHAR(1)
);


-- 3. INSERCION DE DATOS
INSERT INTO CONTROL_STOCK_LIBROS
SELECT 
    SQ_CONTROL_STOCK.NEXTVAL, -- La secuencia va AFUERA
    DATOS.*
FROM (
    -- ADENTRO: Toda la lógica de agrupamiento y cálculo
    SELECT 
        L.libroid,
        L.nombre_libro,
        -- TOTAL EJEMPLARES (Subconsulta)
        (SELECT COUNT(*) FROM SYN_EJEMPLAR E WHERE E.libroid = L.libroid) AS TOTAL,
        -- EN PRESTAMO
        COUNT(P.prestamoid) AS PRESTADOS,
        -- DISPONIBLES
        (SELECT COUNT(*) FROM SYN_EJEMPLAR E WHERE E.libroid = L.libroid) - COUNT(P.prestamoid) AS DISPONIBLES,
        -- PORCENTAJKE
        LPAD(ROUND((COUNT(P.prestamoid) / NULLIF((SELECT COUNT(*) FROM SYN_EJEMPLAR E WHERE E.libroid = L.libroid),0)) * 100, 2),12) AS PCT,
        -- STOCK CRITICO
        CASE 
            WHEN ((SELECT COUNT(*) FROM SYN_EJEMPLAR E WHERE E.libroid = L.libroid) - COUNT(P.prestamoid)) > 2 THEN 'S'
            ELSE 'N'
        END AS CRITICO

    FROM SYN_LIBRO L
    JOIN SYN_PRESTAMO P ON L.libroid = P.libroid
    WHERE 
        TO_CHAR(P.fecha_inicio, 'YYYY') = TO_CHAR(SYSDATE, 'YYYY') - 2
        AND P.empleadoid IN (150, 180, 190)
    GROUP BY L.libroid, L.nombre_libro
    ORDER BY L.libroid
) DATOS;

COMMIT;

SELECT * FROM CONTROL_STOCK_LIBROS;



/*==============================================================================
BLOQUE 3: USER1
VISTA DE MULTAS Y OPTIMIZACION
================================================================================*/

CREATE OR REPLACE VIEW  VW_DETALLE_MULTAS AS
SELECT
    P.prestamoid AS "ID_PRESTAMO",
    INITCAP(A.nombre || ' ' || A.apaterno) AS "NOMBRE_ALUMNO",
    INITCAP(C.descripcion) AS "NOMBRE_CARRERA",
    L.libroid AS "ID_LIBRO",
    LPAD(TO_CHAR(L.precio, '$999G999'),14) AS "VALOR_LIBRO",
    P.fecha_termino AS "FECHA_TERMINO",
    P.fecha_entrega AS "FECHA_ENTREGA",
    
    -- CALCULAMOS LOS DIAS DE ATRASO
    (P.fecha_entrega - P.fecha_termino) AS "DIAS_ATRASO",
    --CALCULAMOS MULTA BASE
    LPAD(TO_CHAR(ROUND(L.precio * 0.03 * (P.fecha_entrega - P.fecha_termino)), '$999G999'),15) AS "VALOR_MULTA",
    --PORCENTAJE DE RABAJA
    (NVL(RM.porc_rebaja_multa, 0) / 100 ) AS "PORCENTAJE_REBAJA_MULTA",
    --VALOR FINAL REBAJADO
    LPAD(TO_CHAR(
        ROUND(
            (L.precio * 0.03 * (P.fecha_entrega - P.fecha_termino)) - 
            ((L.precio * 0.03 *  (P.fecha_entrega - P.fecha_termino)) * NVL(RM.porc_rebaja_multa, 0) / 100)
        ), '$999G999'
    ),15) AS "VALOR_REBAJADO"
FROM PRESTAMO P
    JOIN ALUMNO A ON P.alumnoid = A.alumnoid
    JOIN CARRERA C ON A.carreraid = C.carreraid
    JOIN LIBRO L ON P.libroid = L.libroid
    -- ESTE LEFT JOIN PORQUE NO TODAS LAS CARRERAS TIENEN REBAJA
    LEFT JOIN REBAJA_MULTA RM ON C.carreraid = RM.carreraid
WHERE
    --PRIMER FILTRO, PRESTRAMOS TERMINADOS HACE 2 AÑOS
   TO_CHAR(P.fecha_termino, 'YYYY') = TO_CHAR(ADD_MONTHS(SYSDATE, -24), 'YYYY')
    --SEGUNDO FILTRO, SOLO ENTREGADOS CON ATRASO
    AND P.fecha_entrega > P.fecha_termino
--ORDENAMOS POR LA FECHA DE ENTREGA DESCENDENTE
ORDER BY
    P.fecha_entrega DESC;


DROP VIEW VW_DETALLE_MULTAS;
-- VALIDACION VISUAL DE LA VISTA CREADA
SELECT * FROM VW_DETALLE_MULTAS;
--------------------------------------------------------------------------------------------
/* OPTIMIZACION, INDEX
OBJ: MEJORAR EL COSTO DE LA CONSULTA EVIANTE FULL SCAN
*/

--1.- INDICE BASADO EN FUNCION PARA EL FILTRO DE AÑO
CREATE INDEX IDX_PRESTAMO_FECHA_FUNC
ON PRESTAMO(TO_CHAR(fecha_termino, 'YYYY'));

--2. INDICE NORMAL PARA LA LLAVE FORANEA, AQUI AYUDAMOS AL JOIN CON LIBRO O ALUMN
CREATE INDEX IDX_PRESTAMO_LIBRO
ON PRESTAMO(libroid);

COMMIT;
    
