--TODO EL CODIGO, ORDENADO POR ETAPAS


/*------------------------------------
BLOQUE 1: USUARIO ADMIN
CASO 1:  ESTRATEGIA DE SEGUIRDAD
-----------------------------------*/
--1.- CREACION DE ROLES
CREATE ROLE PRY2205_ROL_D; -- ROL DESARROLLADOR
CREATE ROLE PRY2205_ROL_C; -- ROL CONSULTOR

/*--2.- CREACION DE USUARIOS ESTE USUARIO SE DEJA ASI COMENTADO, PORQUE HAY QUE CARGAR EL POBLAMIENTO
--USUARIO OWNER 
CREATE USER PRY2205_EFT IDENTIFIED BY "Duoc.2025.EFT"
DEFAULT TABLESPACE DATA
QUOTA UNLIMITED ON DATA;*/

--USUARIO DESARROLLADOR
CREATE USER PRY2205_EFT_DES IDENTIFIED BY "Duoc.2025.DES"
DEFAULT TABLESPACE DATA
QUOTA 100M ON DATA;

--USUARIO CONSULTOR
CREATE USER PRY2205_EFT_CON IDENTIFIED BY "Duoc.2025.CON"
DEFAULT TABLESPACE DATA
QUOTA 5M ON DATA;

--ASIGNACION DE PRIVILEGIOS A EFT SE QUEDARA ASI COMENTADO PORQUE HAY QUE CARGAR EL POBLAMIENTO Y DEMORA BASTANTE
--GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE ANY INDEX, CREATE SYNONYM, CREATE PUBLIC SYNONYM, DROP PUBLIC SYNONYM TO PRY2205_EFT;
--PRIVILEGIOS ROL DESARROLLADOR
GRANT CREATE SESSION, CREATE VIEW, CREATE PROFILE, CREATE USER TO PRY2205_ROL_D;
--ROL CONSUTLRO
GRANT CREATE SESSION TO PRY2205_ROL_C;

--ASIGNACION DE ROLES A USUARIOS
GRANT PRY2205_ROL_D TO PRY2205_EFT_DES;
GRANT PRY2205_ROL_C TO PRY2205_EFT_CON;

COMMIT;

===================================================================================================================================================================
===================================================================================================================================================================
/*----------------------------------------------------------------------------
BLOQUE 2: SINONIMOS Y PERMISOS USER_EFT
--------------------------------------------------------------------------------*/

--1. CREAMOS SINONIMOS PUBLICOS, PARA OCULTAR EL ESQUEMA DUEÑO
CREATE OR REPLACE PUBLIC SYNONYM PROFESIONAL FOR PRY2205_EFT.PROFESIONAL; 
CREATE OR REPLACE PUBLIC SYNONYM ASESORIA FOR PRY2205_EFT.ASESORIA;
CREATE OR REPLACE PUBLIC SYNONYM EMPRESA FOR PRY2205_EFT.EMPRESA;
CREATE OR REPLACE PUBLIC SYNONYM COMUNA FOR PRY2205_EFT.COMUNA;
CREATE OR REPLACE PUBLIC SYNONYM PROFESION FOR PRY2205_EFT.PROFESION;
CREATE OR REPLACE PUBLIC SYNONYM AFP FOR PRY2205_EFT.AFP;
CREATE OR REPLACE PUBLIC SYNONYM ISAPRE FOR PRY2205_EFT.ISAPRE;
CREATE OR REPLACE PUBLIC SYNONYM RANGOS_SUELDOS FOR PRY2205_EFT.RANGOS_SUELDOS;
CREATE OR REPLACE PUBLIC SYNONYM TIPO_CONTRATO FOR PRY2205_EFT.TIPO_CONTRATO;
CREATE OR REPLACE PUBLIC SYNONYM CARTOLA_PROFESIONALES FOR PRY2205_EFT.CARTOLA_PROFESIONALES;
CREATE OR REPLACE PUBLIC SYNONYM VW_EMPRESAS_ASESORADAS FOR PRY2205_EFT.VW_EMPRESAS_ASESORADAS;


/* 2. DAMOS PERMISOS A LOS ROLES
EL DESARROLLADOR (CON ROL_D) NECESITA LLER LAS TABLAS BASE Y ESCRIBIR EN LA CARTOLA
*/
 GRANT SELECT ON PROFESIONAL TO PRY2205_ROL_D;
 GRANT SELECT ON PROFESION TO PRY2205_ROL_D;
 GRANT SELECT ON ISAPRE TO PRY2205_ROL_D;
 GRANT SELECT ON TIPO_CONTRATO TO PRY2205_ROL_D;
 GRANT SELECT ON RANGOS_SUELDOS TO PRY2205_ROL_D;

 
 --PERMISO TOTAL SOBRE LA TABLA DE REPORTE PARA EL DESARROLLADOR
 GRANT SELECT, INSERT, UPDATE, DELETE ON CARTOLA_PROFESIONALES TO PRY2205_ROL_D;
 
 --PERMISO PARA QUE DESARROLLADOR HAGA VIVISBLE PARA DEMAS USUARIOS
 GRANT SELECT ON CARTOLA_PROFESIONALES TO PRY2205_EFT_DES WITH GRANT OPTION;
===================================================================================================================================================================
===================================================================================================================================================================
/*BLOQUE 3 USER_DES
CASO2: INFORME DE REMUNERACIONES*/

--INSERSION MASIVA USANDO SELECT Y JOINS
INSERT INTO CARTOLA_PROFESIONALES(
    RUT_PROFESIONAL,
    NOMBRE_PROFESIONAL,
    PROFESION,
    ISAPRE,
    SUELDO_BASE,
    PORC_COMISION_PROFESIONAL,
    VALOR_TOTAL_COMISION,
    PORCENTATE_HONORARIO,
    BONO_MOVILIZACION,
    TOTAL_PAGAR
)
SELECT
    P.RUTPROF,
    INITCAP(P.NOMPRO || ' ' || P.APPPRO || ' ' || P.APMPRO) AS NOMBRE,
    PR.NOMPROFESION,
    I.NOMISAPRE,
    P.SUELDO,
    NVL(P.COMISION, 0),
    --CALCULO DEL VALOR COMISION
    ROUND(P.SUELDO * NVL(P.COMISION, 0)) AS VAL_COMISION,
    --CACULO DE MONTO DE HONORARIOS
    ROUND(P.SUELDO * (NVL(RS.HONOR_PCT, 0) /100 )) AS VAL_HONORARIO,
    --CALCULO BONO MOVILIZACION
    CASE TC.NOMTCONTRATO
        WHEN 'Indefinido Jornada Completa' THEN 150000
        WHEN 'Indefinido Jornada Parcial' THEN 120000
        WHEN 'Plazo Fijo' THEN 60000
        WHEN 'Honorarios' THEN 50000
        ELSE 0
    END AS BONO_MOV,
    --TOTAL A PAGAR
    ROUND(
        P.SUELDO +
        (P.SUELDO * NVL(P.COMISION, 0)) +
        (P.SUELDO * (NVL(RS.HONOR_PCT, 0) /100)) +
        CASE TC.NOMTCONTRATO
            WHEN 'Indefinido Jornada Completa' THEN 150000
            WHEN 'Indefinido Jornada Parcial'  THEN 120000
            WHEN 'Plazo fijo'                  THEN 60000
            WHEN 'Honorarios'                  THEN 50000
            ELSE 0
        END
    ) AS TOTAL
FROM PROFESIONAL P
    JOIN PROFESION PR ON P.IDPROFESION = PR.IDPROFESION
    JOIN ISAPRE I ON P.IDISAPRE = I.IDISAPRE
    JOIN TIPO_CONTRATO TC ON P.IDTCONTRATO = TC.IDTCONTRATO
-- JOIN NONEQUI PARA BUSCAR EL RANDO DE SUELDO
    LEFT JOIN RANGOS_SUELDOS RS ON P.SUELDO BETWEEN RS.S_MIN AND RS.S_MAX
ORDER BY
    PR.NOMPROFESION,
    P.SUELDO DESC,
    P.COMISION,
    P.RUTPROF;
COMMIT;

-- 2. DAR PERMISO AL CONSULTOR
GRANT SELECT ON CARTOLA_PROFESIONALES TO PRY2205_EFT_CON;


-- VALIDAMOS CON AL VISTA DE LA TABLA
SELECT * FROM CARTOLA_PROFESIONALES;

===================================================================================================================================================================
===================================================================================================================================================================
/*BLOQUE 4: USER_EFT
 VISTA DE EMPRESAS Y PROMOCIONES
 OPTIMIZACION DE INDICES*/
 
 -- CREAREMOS LAS VISTAS CON LA LOGICA DE NEGOCIOS
CREATE OR REPLACE VIEW VW_EMPRESAS_ASESORADAS AS
SELECT
    -- RUT con formato 
    TO_CHAR(E.RUT_EMPRESA, 'FM99G999G999') || '-' || E.DV_EMPRESA AS "RUT_EMPRESA",
    E.NOMEMPRESA AS "NOMBRE_EMPRESA",
    E.IVA_DECLARADO AS "IVA",
    -- AÑOS EXISTENCIA
    EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM E.FECHA_INICIACION_ACTIVIDADES) AS "ANIOS_EXISTENCIA",
    
    -- TOTAL ASEOSIRAS
    ROUND(COUNT(A.RUTPROF) / 12) AS "TOTAL_ASESORIAS_ANUALES",    
    --DEVOLUCION IVA
    ROUND((E.IVA_DECLARADO * ROUND(COUNT(A.RUTPROF)/12))/100) AS "DEVOLUCION_IVA",
    
    -- TIPO CLIENTE
    CASE 
        WHEN ROUND(COUNT(A.RUTPROF)/12) > 5 THEN 'CLIENTE PREMIUM'
        WHEN ROUND(COUNT(A.RUTPROF)/12) BETWEEN 3 AND 5 THEN 'CLIENTE'
        ELSE 'CLIENTE POCO CONCURRIDO'
    END AS "TIPO_CLIENTE",
    
    -- PROMOCIONES
    CASE
        WHEN ROUND(COUNT(A.RUTPROF)/12) > 5 THEN
            CASE
                WHEN ROUND(COUNT(A.RUTPROF)/12) >= 7 THEN '1 ASESORIA GRATIS'
                ELSE '1 ASESORIA 40% DE DESCUENTO'
            END
        WHEN ROUND(COUNT(A.RUTPROF)/12) BETWEEN 3 AND 5 THEN
            CASE
                WHEN ROUND(COUNT(A.RUTPROF)/12) = 5 THEN '1 ASESORIA 30% DE DESCUENTO'
                ELSE '1 ASESORIA 20% DE DESCUENTO'
            END
        ELSE 'CAPTAR CLIENTE'
    END AS "CORRESPONDE"

FROM EMPRESA E
    JOIN ASESORIA A ON E.IDEMPRESA = A.IDEMPRESA
WHERE
    EXTRACT(YEAR FROM A.FIN) = EXTRACT(YEAR FROM SYSDATE) - 1
GROUP BY
    E.RUT_EMPRESA, E.DV_EMPRESA, E.NOMEMPRESA, E.IVA_DECLARADO, E.FECHA_INICIACION_ACTIVIDADES
ORDER BY
    E.NOMEMPRESA ASC;
    
    
--VALIDESMO PROBANDO ANTES DE REALIZAR LO INDEX CON F10


--OPTMIZACION, INDICE BASADO EN FUNCION PARA ACELERAR EL FILTRO DE AÑO
CREATE INDEX IDX_ASESORIA_ANIO_FIN ON ASESORIA(EXTRACT(YEAR FROM FIN));
--ADEMAS ENTRE EMPRESA Y ASESORIA USANDO ESTE INDICE ACELERA DRASTICAMENTE EL CRUCE DE DATOS EVIATNDO RECORRIDO INNECESARIOS
CREATE INDEX IDX_ASESORIA_EMPRESA_FK ON ASESORIA(IDEMPRESA);

-- DAR PERMISO AL CONSULTOR PARA QUE PUEDA VER EL INFORME
GRANT SELECT ON VW_EMPRESAS_ASESORADAS TO PRY2205_ROL_C;

COMMIT;

-- VALIDACION
SELECT * FROM VW_EMPRESAS_ASESORADAS;
===================================================================================================================================================================
===================================================================================================================================================================
/*CONSUTLOR USER_CON
USER CONSULTOR*/


SHOW USER;

-- 2. Consultar el Informe del Caso 2 

SELECT * FROM CARTOLA_PROFESIONALES ORDER BY TOTAL_PAGAR DESC;

-- 3. Consultar la Vista del Caso 3 (Validar permiso del Dueño SI DA ERROR)

SELECT * FROM VW_EMPRESAS_ASESORADAS ORDER BY NOMBRE_EMPRESA;

